{{- $appName := include "pdns-admin.name" . -}}
{{- $fullName := include "pdns-admin.fullname" . -}}
{{- $commonLabels := include "pdns-admin.commonLabels" . -}}
{{- $matchLabels := include "pdns-admin.matchLabels" . -}}
{{- $appBackend := include "pdns-admin.appBackend" . -}}

{{- with .Values.components.static }}
{{- $port := .service.port -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- $commonLabels | nindent 4 }}
    component: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- $matchLabels | nindent 6 }}
      component: {{ .name }}
  template:
    metadata:
      labels:
        {{- $commonLabels | nindent 8 }}
        component: {{ .name }}
    spec:
      imagePullSecrets:
      - name: {{ .image.pullSecretName }}
      containers:
      - name: {{ $.Chart.Name }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        env:
        - name: NGINX_BACKEND
          value: {{ $appBackend | quote }}
        - name: SERVICE_TAGS
          value: {{ $.Values.serviceTags | quote }}
        - name: SERVICE_REGION
          value: {{ $.Values.serviceRegion | quote }}
        - name: SERVICE_NAME
          value: {{ $fullName | quote }}
        ports:
          - containerPort: {{ $port }}
            protocol: TCP
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        {{- if .resources }}
        resources:
{{- toYaml .resources | nindent 10 }}
        {{- end }}
    {{- if .nodeSelector }}
      nodeSelector:
{{ toYaml .nodeSelector | indent 8 }}
    {{- end }}
{{ end -}}
