{{- if .Values.secret.enabled -}}

{{- $appName := include "pdns-admin.name" . -}}
{{- $fullName := include "pdns-admin.fullname" . -}}
{{- $commonLabels := include "pdns-admin.commonLabels" . -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- $commonLabels | nindent 4 }}
type: Opaque
data:
  mysql_db_password: {{ .Values.mysql.dbPassword | squote | b64enc }}
  api_key: {{ .Values.powerdns.apiKey | squote | b64enc }}
  ldap_password: {{ .Values.ldap.password | squote | b64enc }}

{{- end -}}
